#!/bin/bash
# ==============================================================================
# Automated Android Environment Setup Script
# Generated by IDEaz
#
# Description:
# This script automatically prepares a Linux environment for Android development.
# It checks for and installs necessary prerequisites (wget, unzip),
# ensures Java (OpenJDK 17) is installed, and downloads/configures the
# Android Command Line Tools and basic SDK packages. Finally, it updates
# the user's .bashrc with the required environment variables.
#
# Usage:
# Run this script directly from the terminal: `./setup_env.sh`
# ==============================================================================

set -e # Exit immediately if a command exits with a non-zero status.

# ------------------------------------------------------------------------------
# Function: command_exists
# Description: Checks if a given command is available in the system's PATH.
# Arguments: $1 - The command to check (e.g., 'wget', 'java')
# Returns: 0 (true) if the command exists, 1 (false) otherwise.
# ------------------------------------------------------------------------------
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

echo "Starting environment setup..."

# ------------------------------------------------------------------------------
# Phase 0: Prerequisites
# Ensures that basic utilities required for downloading and extracting the
# Android SDK are present on the system. Supports apt, yum, and apk.
# ------------------------------------------------------------------------------
if ! command_exists wget || ! command_exists unzip; then
    echo "Installing prerequisites (wget, unzip)..."
    if command_exists apt-get; then
        sudo apt-get update
        sudo apt-get install -y wget unzip
    elif command_exists yum; then
        sudo yum install -y wget unzip
    elif command_exists apk; then
        sudo apk add wget unzip
    fi
fi

# ------------------------------------------------------------------------------
# Phase 1: Java Setup
# Android development requires Java. This project standardizes on JDK 17.
# The script checks for 'java'. If not found, it attempts to install OpenJDK 17
# using the system's package manager.
# ------------------------------------------------------------------------------
if ! command_exists java; then
    echo "Java not found. Installing OpenJDK 17..."
    if command_exists apt-get; then
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
    elif command_exists yum; then
        sudo yum install -y java-17-openjdk
    elif command_exists apk; then
        sudo apk add openjdk17
    else
        echo "Error: Package manager not found. Please install JDK 17 manually."
        exit 1
    fi
else
    echo "Java is already installed."
fi

# Verify Java version (prints to console so the user/agent can confirm)
java -version

# ------------------------------------------------------------------------------
# Phase 2: Android SDK Setup
# Downloads the Android Command Line Tools and uses 'sdkmanager' to install
# the necessary platform tools and build tools.
# Defaults installation to $HOME/Android/sdk.
# ------------------------------------------------------------------------------
export ANDROID_HOME="$HOME/Android/sdk"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"

if [ ! -d "$ANDROID_HOME" ]; then
    echo "Android SDK not found. Installing..."
    mkdir -p "$ANDROID_HOME/cmdline-tools"

    # Download Command Line Tools
    CMD_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    wget -q "$CMD_TOOLS_URL" -O android_tools.zip
    unzip -q android_tools.zip -d "$ANDROID_HOME/cmdline-tools"
    rm android_tools.zip

    # Move to correct structure: cmdline-tools/latest
    mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"

    # Install basic SDK packages
    yes | sdkmanager --licenses
    sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
else
    echo "Android SDK directory exists."
fi

# ------------------------------------------------------------------------------
# Phase 3: Environment Variables
# Updates the user's ~/.bashrc file to persistently set ANDROID_HOME and
# update the PATH variable so Android tools can be executed from anywhere.
# ------------------------------------------------------------------------------
if [ -f "$HOME/.bashrc" ]; then
    if ! grep -q "ANDROID_HOME" "$HOME/.bashrc"; then
        echo "Adding environment variables to .bashrc..."
        echo '' >> "$HOME/.bashrc"
        echo 'export ANDROID_HOME=$HOME/Android/sdk' >> "$HOME/.bashrc"
        echo 'export ANDROID_SDK_ROOT=$ANDROID_HOME' >> "$HOME/.bashrc"
        echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools' >> "$HOME/.bashrc"
    fi
fi

echo "Environment setup complete."